name: charts_common_cf
version: 0.10.3+cf
description: A common library for charting packages.
homepage: https://github.com/exafree/charts_cf

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  collection: ^1.14.5
  intl: '>=0.15.2 < 0.17.0'
  logging: ^0.11.4
  meta: ^1.1.1
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^4.0.0
  test: ^1.5.3
